image:
  repository: europe-central2-docker.pkg.dev/gogke-main-0/private-docker-images/gogke/kuard
  tag: 0.0.0

serviceAccountName: ""

configEnvs: {}
secretConfigEnvs: {}
configFiles: {}
secretConfigFiles: {}

httpServer:
  minReplicas: 1
  maxReplicas: 1
