service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [k8sattributes, batch]
      exporters: [otlphttp/loki]
    metrics:
      receivers: [otlp]
      processors: [k8sattributes, batch]
      exporters: [otlphttp/mimir]
    traces:
      receivers: [otlp]
      processors: [k8sattributes, batch]
      exporters: [otlphttp/tempo]

  extensions:
    - health_check
