name: delete-gke-node-pools
on:
  schedule:
    - cron: "0 12,14,16,18,20,22 * * *"
jobs:
  delete-gke-node-pools:
    name: delete-gke-node-pools
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/gogcp-devcontainer:0.0.1
    steps:
      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: gcloud container node-pools delete
        run: gcloud --quiet container node-pools delete "gogke-test-7" --location="europe-central2-a" --cluster="gogke-test-7" --project="gogke-test-0" || true
