name: docker-images/kuard
on:
  pull_request:
    paths:
      - ".github/workflows/docker-images-kuard.gotmpl.yaml"
      - "docker-images/kuard/**"
      - "!docker-images/kuard/README.md"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker-images-kuard.gotmpl.yaml"
      - "docker-images/kuard/**"
      - "!docker-images/kuard/README.md"
      - "!docker-images/kuard/container-structure-test.yaml"
jobs:
  docker-images-kuard:
    name: docker-images/kuard
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/gogcp-devcontainer:0.0.0
    permissions:
      contents: write
      id-token: write
      packages: write
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - run: git config --system --add safe.directory /__w/gogcp/gogcp
      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          cleanup_credentials: true
      - name: docker buildx
        uses: docker/setup-buildx-action@v3
      - name: docker auth (Google Artifact Registry)
        run: gcloud auth configure-docker "europe-central2-docker.pkg.dev"
      - name: docker auth (Docker Hub)
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker auth (GitHub Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: ./scripts/docker-image build "kuard"
      - name: test
        run: ./scripts/docker-image test "kuard"
      - if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        name: pre-publish
        run: ./scripts/docker-image pre-publish "kuard"
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: publish
        run: ./scripts/docker-image publish "kuard"
      - name: show
        run: ./scripts/docker-image show "kuard"
