name: scopes/kuard/terraform-modules/kuard
on:
  pull_request:
    paths:
      - ".github/workflows/scopes-kuard-terraform-modules-kuard.gotmpl.yaml"
      - "scopes/kuard/terraform-modules/kuard/**"
      - "!scopes/kuard/terraform-modules/kuard/README.md"
  push:
    branches:
      - main
    paths:
      - "scopes/kuard/terraform-modules/kuard/**"
      - "!scopes/kuard/terraform-modules/kuard/README.md"
jobs:
  scopes-kuard-terraform-modules-kuard:
    name: scopes/kuard/terraform-modules/kuard
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/gogcp-devcontainer:0.1.0
    permissions:
      contents: write
      id-token: write
    env:
      TF_IN_AUTOMATION: 1
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: git clone fix
        run: git config --system --add safe.directory /__w/gogcp/gogcp
      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          cleanup_credentials: true
      - name: cache
        uses: actions/cache@v4
        with:
          key: scopes-kuard-terraform-modules-kuard
          path: |
            scopes/kuard/terraform-modules/kuard/.terraform
      - name: test
        run: ./scripts/terraform-module test "scopes/kuard/terraform-modules/kuard"
      - name: init
        run: terraform -chdir="scopes/kuard/terraform-modules/kuard" init -input=false
      - name: validate
        run: terraform -chdir="scopes/kuard/terraform-modules/kuard" validate
      - if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        name: plan
        run: terraform -chdir="scopes/kuard/terraform-modules/kuard" plan -input=false
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: apply
        run: terraform -chdir="scopes/kuard/terraform-modules/kuard" apply -input=false -auto-approve
