name: scopes/kuard/terraform-submodules/kuard
on:
  pull_request:
    paths:
      - ".github/workflows/scopes-kuard-terraform-submodules-kuard.gotmpl.yaml"
      - "scopes/kuard/terraform-submodules/kuard/**"
      - "!scopes/kuard/terraform-submodules/kuard/README.md"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/scopes-kuard-terraform-submodules-kuard.gotmpl.yaml"
      - "scopes/kuard/terraform-submodules/kuard/**"
      - "!scopes/kuard/terraform-submodules/kuard/README.md"
jobs:
  scopes-kuard-terraform-submodules-kuard:
    name: scopes/kuard/terraform-submodules/kuard
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/gogcp-devcontainer:0.0.2
    permissions:
      contents: write
      id-token: write
    env:
      TF_IN_AUTOMATION: 1
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: git clone fix
        run: git config --system --add safe.directory /__w/gogcp/gogcp
      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          cleanup_credentials: true
      - name: cache
        uses: actions/cache@v4
        with:
          key: scopes-kuard-terraform-submodules-kuard
          path: |
            scopes/kuard/terraform-submodules/kuard/.terraform
            scopes/kuard/terraform-submodules/kuard/.terraform.lock.hcl
      - name: build
        run: ./scripts/terraform-submodule build "kuard" "kuard"
      - name: test
        run: ./scripts/terraform-submodule test "kuard" "kuard"
      - if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        name: pre-publish
        run: ./scripts/terraform-submodule pre-publish "kuard" "kuard"
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: publish
        run: ./scripts/terraform-submodule publish "kuard" "kuard"
      - name: show
        run: ./scripts/terraform-submodule show "kuard" "kuard"
