name: terraform-submodules/helm-release
on:
  pull_request:
    paths:
      - "terraform-submodules/helm-release/**"
      - "!terraform-submodules/helm-release/README.md"
  push:
    branches:
      - main
    paths:
      - "terraform-submodules/helm-release/**"
      - "!terraform-submodules/helm-release/README.md"
jobs:
  terraform-submodules-helm-release:
    name: terraform-submodules/helm-release
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/gogcp-devcontainer:0.0.0
    permissions:
      contents: write
      id-token: write
    env:
      TF_IN_AUTOMATION: 1
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          cleanup_credentials: true
      - name: cache
        uses: actions/cache@v4
        with:
          key: terraform-submodules-helm-release
          path: |
            terraform-submodules/helm-release/.terraform
            terraform-submodules/helm-release/.terraform.lock.hcl
      - name: build
        run: ./scripts/terraform-submodule build "helm-release"
      - name: test
        run: ./scripts/terraform-submodule test "helm-release"
      - if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        name: pre-publish
        run: ./scripts/terraform-submodule pre-publish "helm-release"
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: publish
        run: ./scripts/terraform-submodule publish "helm-release"
      - name: show
        run: ./scripts/terraform-submodule show "helm-release"
